[package]
name = "cpide"
version = "0.1.0"
authors = ["mmurphy316 <mashumafi@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.1.1"
actix-files = "0.2.1"
serde = "1.0.110"
env_logger = "0.7.1"
log = "0.4.8"
rand = "0.7.3"
difference = "2.0"
rayon = "1.1"
